language: node_js
node_js: node
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 15
  - mongo ironjiTest --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - yarn install
  - yarn test
services:
  - mongodb